
# ===============================
# CONFIGURACION DE LA BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/global_yofi?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACION DE PUERTO
# ===============================
server.port=${PORT:8080}

# ===============================
# CONFIGURACION CARPETA PARA GUARDAR IMAGENES
# ===============================
app.upload.dir=uploads

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG


# ===============================
# CONFIGURACION DE PUERTO
# ===============================
server.port=${PORT:8080}

# ===============================
# CONFIGURACION CARPETA PARA GUARDAR IMAGENES
# ===============================
app.upload.dir=uploads

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

# ===============================
# CONFIGURACION DE LA BASE DE DATOS (RAILWAY)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}